theme: jekyll-theme-minimal
title: CV 
description: Ismail CELEN's CV
Name: jekyll-theme-minimal
Tagline: jekyll-theme-minimal
Dev Platforms Username: jekyll-theme-minimal 
Current Work: jekyll-theme-minimal
Portfolio: jekyll-theme-minimal